### ISSUE TITLE
Does not change VR LOD Settings

### ISSUE THREAD

**Issue by Divij13** [Fragtality/DynamicLOD#1]
Hello, I gave this a go and managed to get it working well in 2D!

However the TLOD and OLOD values only change in the 2D sim settings, not the VR sim settings.

Any plans to add that functionality? This would be great for VR!

**Comment by Fragtality** [comment]
Nope, not planned.

And "2D" is a bit wrong. VR is also just a 2D Projection of a 3D Scene, you just have two different 2D Projections so that your Brain can be tricked.

**Comment by Divij13** [comment]
Understood thanks. 

Does having different settings in the separate menus (Monitor & VR) for LOD's create any issues?

Thanks for the great work!

**Comment by Fragtality** [comment]
Don't know, I don't have a VR Headset.
But as you see in the UserCfg.opt, it is two different Parameter (two different Sets for each Mode) - don't know why Asobo made it that Way when the Settings need to be the same in both Modes. Of course there is always the Chance that Asobo messed up something and did not fix it yet (ever?) 😅

**Comment by Divij13** [comment]
From my understanding of reading about this on the official MSFS forums, the only mirror between Monitor and VR is for the mouse clicking. So apparently both values of LOD (Monitor & VR) are independent.  

If there is any way that us VR users could be able to tweak this application to change the VR Settings Values for LOD instead of the Monitor Setting values, please do let me know. 

This would be an absolute game changer for many VR users!

Apologies for the persistence and many thanks once again.

**Comment by Fragtality** [comment]
Hey, the Code and Method are open - you're free to dig into that and tell me the Offsets/Pointers to use afterwards 😉

**Comment by Divij13** [comment]
I wouldn't have the faintest clue where to start digging. 
But I'm hoping that someone far more clever than me could give it a go and figure it out :)

**Comment by Avidean** [comment]
Any plans on fixing the thing that's a bit wrong about it in an update? It works like a charm. Could be the biggest thing yet for improved performance on approach and on the ground.

**Comment by virtualisoftware** [comment]
FYI, there are two offsets (they seem to be doing the same thing) which you can read to know the VR mode is active, which might be useful to read, to make the switch between settings automatic.

FlightSimulator.exe+765B694
FlightSimulator.exe+765B704

Both are DWORD ( 4 bytes ), and the value it's 1 if VR Mode is enabled, otherwise they are 0.
