### ISSUE TITLE
Application window cannot be resized

### ISSUE THREAD

**Issue by munala** [Fragtality/DynamicLOD#11]
I have two monitors, one 1080p, the other one 1440p. I set many TLOD entries using the 1440p monitor but wanted to keep the app on the 1080p monitor. On the 1080p monitor, a portion of the app goes off-screen and there's no way of resizing the window to fit and allow scrolling. Ideally, the window should be resizeable and the overflowing content should be scrollable. Otherwise, the number of pairs you can modify is limited to the screen's height. Ignore the very many TLOD pairs, I'm doing some testing.

On 1440p screen
![Screenshot 2024-01-11 162126](https://github.com/Fragtality/DynamicLOD/assets/22608948/878b06dd-a8f8-406a-9ad4-ae728819e2a9)

On 1080p screen
![Screenshot 2024-01-11 162742](https://github.com/Fragtality/DynamicLOD/assets/22608948/c243c895-2d6b-4738-97bd-416638f9e4d0)

**Comment by Fragtality** [comment]
Reduce Pairs.
That is just pure Madness.
