### ISSUE TITLE
Cannot Uninstall

### ISSUE THREAD

**Issue by betterpilot** [Fragtality/DynamicLOD#12]
Hello, 

I am trying to uninstall the app. I went to C:\Users\Name\AppData\Roaming\DynamicLOD and Deleted the Dynamic LOD folders but now I am getting a windows error sound every time my Sim opens because it is trying to open the app and it is not there. 

I reinstalled the program and it's auto opening now even though I have autostart unselected. I can't seem to get rid of the program or it's wanting to open when I open on MSFS even after I delete the app. 

Please help!

**Comment by KolosovV** [comment]
GD!
First way: Download installer and start it then you will see button "Uninstall" press it and that's it. 
Second way: Open fsuipc.ini or exe.xml (depends what you select during installation) and delete DynamicLOD strings.

**Comment by betterpilot** [comment]
Thanks for getting back,

I removed the Dynamic LOD lines from my FSUIPC .ini and the error sound is still occurring. I am guessing I need to find the exe.xml. Is this the exe.xml for MSFS, FSUIPC, or DynamicLOD? Please let me know which one and where I can find it. 

I reinstalled the program and did not see any uninstall option on the Installer, but maybe I am missing something?

![image](https://github.com/Fragtality/DynamicLOD/assets/72628364/6e5be920-fb29-48c2-85cb-3e12a20cbcb3)

Thanks!

**Comment by betterpilot** [comment]
Found the exe.xml and deleted the launch command here: C:\Users\Name\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache

Thanks for the help!
