### ISSUE TITLE
Closing the program doesn't kill its respective DynamicLOD.exe process.

### ISSUE THREAD

**Issue by Smiths76245** [Fragtality/DynamicLOD#2]
Hi, thank you for making this fantastic program. I have noticed that closing the program doesn't 'fully' close it out unless I force quit from Task Manager. 

Running Windows 10 21H2 19043.3208 , process is excluded from Defender.

**Comment by Fragtality** [comment]
All manual and automatic Ways to close the Program (not equal closing Window) work as intended.
