### ISSUE TITLE
DynamicLOD status/setting application window doesnt pop-up

### ISSUE THREAD

**Issue by mmbooij** [Fragtality/DynamicLOD#4]
Slight problem: i did all installations and all worked as a dream on win11 pc, with my MSFS PMDG 737 (Intel Core i9 met GeForce RTX 3080 - 32GB RAM with 3 x 2K monitors, including DLSS Super resolution - Quality, All ultra, avg 30FPS) 

But.....................  it worked just once!!!  I can still start MSFS & DynamicLOD, both are visible active in the windows task manager, but the DynamicLOD status/setting application window doesnt pop-up, no matter what order I restart in admin mode. I even re-installed, re-booted, no luck.

**Comment by Fragtality** [comment]
From the Readme:
![image](https://github.com/Fragtality/DynamicLOD/assets/78614902/29014866-94ce-4766-9dd4-f8383fb52b36)

There is Guidance on Run-as-Admin in the Readme.

Maybe the config File is messed up, try deleting it and install again.

**Comment by gcaws** [comment]
Exactly the same as mmbooij status comment. Awesome app the one time it ran. Config is fine and unmodified. Not sure what to do or I would fix it myself. Happy to pay for this app as it does make a difference. Cheers and Thanks to Fragtality for making the effort.

**Comment by gcaws** [comment]
I got it running. I copied my "DynamicLOD.config" file from to root "DynamicLOD" directory to the "bin" subdirectory. I renamed the "DynamicLOD.config" file already in the "bin" directory (so basically a 2nd one) by adding ".old" at the end. Not sure why it worked but happy it did. Cheers  (My file path--> C:\Users\Greg\AppData\Roaming\DynamicLOD)

**Comment by Fragtality** [comment]
That does not make Sense technically, since that Config File in bin is only used as fallback when the Config File in the root does not exist. And if you really only copied it from root, it should not have made any difference.

And deleting the Config and running the Installer again made no Difference?

**Comment by gcaws** [comment]
Didn't try to reinstall. Effectively I have two identical config files now one in bin and one in the root. Shut down and rebooted and no issues now. Just what I did. I could experiment if you want? But like you say, it's just more stuff to do. Anyways, thank-you for doing this as I know its non-trivial. Cheers.

**Comment by gcaws** [comment]
This is the YouTube where I found out about your work. https://www.youtube.com/watch?v=3fy1QkK5PqI&t=289s
